name: live_todo_list
description: Aplikasi manajemen tugas profesional dengan fitur countdown real-time dan penyimpanan lokal.
# Mencegah publikasi tidak sengaja ke pub.dev karena ini adalah aplikasi privat
publish_to: 'none'

version: 1.0.0+1

environment:
  # Menggunakan batasan SDK modern untuk kompatibilitas fitur null-safety
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/img/todo-list.png
  adaptive_icon_background: '#F8FAFC'
  adaptive_icon_foreground: assets/img/todo-list.png
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/img/todo-list.png
